name: smstfy
description: "SMS gateway powered by ntfy"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path: ^1.9.0
  flutter_launcher_icons: ^0.13.1
  animations: ^2.0.11
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.1+1
  sms_advanced:
    git:
      url: https://github.com/EddieKamau/sms_advanced.git
      ref: master
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true